apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik
  data:
  - secretKey: password
    remoteRef:
      key: secrets/authentik/bootstrap
      property: password
  - secretKey: token
    remoteRef:
      key: secrets/authentik/bootstrap
      property: token
  - secretKey: secretkey
    remoteRef:
      key: secrets/authentik/bootstrap
      property: secretkey
