apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-bootstrap
  data:
    - secretKey: password
      remoteRef:
        key: secrets/authentik/bootstrap
        property: password
    - secretKey: token
      remoteRef:
        key: secrets/authentik/bootstrap
        property: token
    - secretKey: secretkey
      remoteRef:
        key: secrets/authentik/bootstrap
        property: secretkey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-postgres
  data:
    - secretKey: username
      remoteRef:
        key: secrets/authentik/postgres
        property: superuser-name
    - secretKey: password
      remoteRef:
        key: secrets/authentik/postgres
        property: superuser-password
