apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  instances: 1
  enableSuperuserAccess: true
  superuserSecret:
    name: authentik-postgres
  storage:
    size: 8Gi
