apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fireflyiii
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fireflyiii-secrets
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: secrets/fireflyiii/config
        property: APP_KEY
    - secretKey: DB_DATABASE
      remoteRef:
        key: secrets/fireflyiii/database
        property: DB_DATABASE
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secrets/fireflyiii/database
        property: DB_PASSWORD
    - secretKey: DB_USERNAME
      remoteRef:
        key: secrets/fireflyiii/database
        property: DB_USERNAME
    - secretKey: STATIC_CRON_TOKEN
      remoteRef:
        key: secrets/fireflyiii/config
        property: STATIC_CRON_TOKEN
  # - secretKey: ACCESS_TOKEN
  #   remoteRef:
  #     key: secrets/fireflyiii/config
  #     property: ACCESS_TOKEN
