apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: attic-data
  namespace: velero
spec:
  schedule: 0 12 */7 * *
  template:
    includedNamespaces:
      - attic
    includedResources:
      - pvc
    snapshotMoveData: true
    ttl: 730h0m0s
