apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    includedNamespaces:
      - authentik
      - vault
      - vaultwarden
      - kamaji
      - golinks
      - powerdns
    includedResources:
      - pvc
    snapshotMoveData: true
    ttl: 160h0m0s
