apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: golinks-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    includedNamespaces:
      - golinks
    includedResources:
      - pvc
      - pv
    snapshotMoveData: true
    ttl: 160h0m0s
