apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: immich-data
  namespace: velero
spec:
  schedule: 0 12 */7 * *
  template:
    includedNamespaces:
      - immich
    includedResources:
      - pvc
    labelSelector:
      matchLabels:
        kustomize.toolkit.fluxcd.io/name: immich
    snapshotMoveData: true
    ttl: 730h0m0s
