apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: kamaji-postgres-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    includedNamespaces:
      - kamaji-system
    includedResources:
      - pvc
    snapshotMoveData: true
    ttl: 160h0m0s
