apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: attic
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/attic
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
