apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h0m0s
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: authentik
      version: "2024.*"
      sourceRef:
        kind: HelmRepository
        name: authentik
  values:
    global:
      env:
      - name: AUTHENTIK_IMPERSONATION
        value: "false"
      - name: AUTHENTIK_BOOTSTRAP_EMAIL
        value: "contact@didactik.labs"
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-postgres
            key: password
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-bootstrap
            key: secretkey
      - name: AUTHENTIK_BOOTSTRAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-bootstrap
            key: password
      - name: AUTHENTIK_BOOTSTRAP_TOKEN
        valueFrom:
          secretKeyRef:
            name: authentik-bootstrap
            key: token
    server:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: root-didactiklabs
        hosts:
        - auth.didactik.labs
        paths:
        - /
        pathType: Prefix
        tls:
        - hosts:
          - auth.didactik.labs
          secretName: authentik-tls
    authentik:
      avatars: none
      log_level: info
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      postgresql:
        host: "{{ .Release.Name }}-postgres"
        name: postgres
        port: 5432
        user: authentik
      redis:
        host: "{{ .Release.Name }}-redis-master"
    postgresql:
      enabled: false
    redis:
      architecture: standalone
      auth:
        enabled: false
      enabled: true
      master:
        persistence:
          enabled: false
    serviceAccount:
      automountServiceAccountToken: true
      create: true
