apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-api
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/apps/cluster-api
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
