apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-api-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/apps/cluster-api/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-api-providers
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/cluster-api/providers
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: cluster-api-operator
