apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/cnpg
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
