apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  install:
    createNamespace: false
  chart:
    spec:
      chart: external-secrets
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  interval: 1h0m0s
  values:
    installCRDs: true
