apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
