apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: golinks
  namespace: flux-system
spec:
  interval: 5m
  path: ./gitops/apps/golinks
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
