apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-gateway-api
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/apps/istio-gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
