apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/apps/istio-gateway-api/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-gateway-api-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/apps/istio-gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: istio-gateway-api-crds
