apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: istio-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: base
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
    pilot:
      env:
        PILOT_ENABLE_ALPHA_GATEWAY_API: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: cni
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: ztunnel
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
