apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kamaji-requirements
  namespace: flux-system
spec:
  interval: 5m
  path: ./gitops/apps/kamaji/requirements
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kamaji
  namespace: flux-system
spec:
  interval: 2m
  path: ./gitops/apps/kamaji/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: kamaji-requirements
