apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: clastix
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamaji
  namespace: flux-system
spec:
  targetNamespace: kamaji-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: kamaji
      version: "0.9.19"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  interval: 1h0m0s
  values:
    installCRDs: true
