apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: clastix
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamaji
  namespace: flux-system
spec:
  targetNamespace: kamaji-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: kamaji
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: clastix
  interval: 1h0m0s
  values:
    image:
      tag: edge-24.12.1
    etcd:
      deploy: false
    datastore:
      enabled: true
      nameOverride: postgres-cnpg
      driver: PostgreSQL
      endpoints: ["kamaji-postgres-rw.kamaji-system.svc:5432"]
      basicAuth:
        usernameSecret:
          name: kamaji-postgres-superuser
          namespace: kamaji-system
          keyPath: username
        passwordSecret:
          name: kamaji-postgres-superuser
          namespace: kamaji-system
          keyPath: password
      tlsConfig:
        enabled: false
        certificateAuthority:
          certificate:
            name: kamaji-postgres-ca
            namespace: kamaji-system
            keyPath: ca.crt
