apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  targetNamespace: openebs
  install:
    createNamespace: true
  chart:
    spec:
      chart: openebs
      version: "3.10.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 1h0m0s
  values:
    mayastor:
      enabled: false