apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pvc-backups
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/apps/pvc-backups
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
