apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/external-secret-operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
