apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unsealer-operator
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/unsealer-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
