apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: vault
      version: 0.31.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  values:
    global:
      tlsDisable: true
    server:
      dataStorage:
        enabled: true
        size: 10Gi
        mountPath: '/vault/data'
        accessMode: ReadWriteOnce
      standalone:
        enabled: '-'
        config: |
          ui = true
          listener "tcp" {
            tls_disable = true
            address = "0.0.0.0:8200"
          }
          storage "file" {
            path = "/vault/data"
          }
      readinessProbe:
        enabled: false
      livenessProbe:
        enabled: false
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: root-didactiklabs
        labels:
          probe: enabled
        pathType: Prefix
        hosts:
          - host: vault.didactik.labs
            paths:
              - /
        tls:
          - secretName: vault-tls
            hosts:
              - vault.didactik.labs
    ui:
      enabled: true
      publishNotReadyAddresses: true
      activeVaultPodOnly: false
      serviceType: 'ClusterIP'
      externalPort: 443
      targetPort: 8200
    injector:
      enabled: false
    csi:
      enabled: false
