apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h0m0s
  url: https://vmware-tanzu.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: velero
      version: "7.1.2"
      sourceRef:
        kind: HelmRepository
        name: velero
  values:
    deployNodeAgent: true
    configuration:
      features: EnableCSI
      backupStorageLocation:
        - bucket: velero
          name: default
          provider: aws
          prefix: csi
          default: true
          config:
            region: minio
            s3ForcePathStyle: true
            s3Url: http://minio.minio.svc:9000
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: minio
            s3ForcePathStyle: true
            s3Url: http://minio.minio.svc:9000
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.1
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      useSecret: true
      existingSecret: minio-credentials
