apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero-ui
  namespace: velero
spec:
  interval: 1h0m0s
  dependsOn:
    - name: velero
      kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1
  chart:
    spec:
      chart: velero-ui
      version: 0.13.3
      sourceRef:
        kind: HelmRepository
        name: velero-ui
  values:
    replicaCount: 1
    image:
      repository: otwld/velero-ui
      pullPolicy: IfNotPresent
    configuration:
      logLevel: "debug"
      general:
        secretPassPhrase:
          useSecret: true
          key: "passphrase"
          existingSecret: "velero-ui"
        veleroNamespace: "velero"
    rbac:
      create: true
      clusterAdministrator: false
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: root-didactiklabs
      labels:
        probe: enabled
      hosts:
        - host: velero.didactik.labs
          paths:
            - path: /
              pathType: Prefix
            - path: /socket.io
              pathType: Prefix
      tls:
        - secretName: velero-ui-tls
          hosts:
            - velero.didactik.labs
    env:
      - name: BASIC_AUTH_ENABLED
        value: "true"
      - name: BASIC_AUTH_USERNAME
        valueFrom:
          secretKeyRef:
            name: velero-ui
            key: username
      - name: BASIC_AUTH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: velero-ui
            key: password
