apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: velero-ui
  namespace: velero
spec:
  interval: 1h0m0s
  url: https://helm.otwld.com
  dependsOn:
    - name: velero
      kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1
