apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-generic
spec:
  parentRefs:
    - name: public
      namespace: istio-system
      sectionName: https
  hostnames:
    - minio.didactiklabs.io
  rules:
    - backendRefs:
        - name: minio-generic
          port: 9001
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-generic-api
spec:
  parentRefs:
    - name: public
      namespace: istio-system
      sectionName: https
  hostnames:
    - s3.didactiklabs.io
  rules:
    - backendRefs:
        - name: minio-generic
          port: 9000
