apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-cloudflare
spec:
  acme:
    email: alanamoyel06@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare-account-key
    solvers:
    - dns01:
        cloudflare:
          email: alanamoyel06@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key-secret
  data:
    - secretKey: api-key
      remoteRef:
        key: secrets/cloudflare
        property: api-key
