apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-didactiklabs
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-didactiklabs
  secretName: root-didactiklabs
  privateKey:
    algorithm: RSA
    size: 4096
  duration: 87600h
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-didactiklabs
spec:
  ca:
    secretName: root-didactiklabs