resources:
  - upstream/
  - internal-issuer.yaml
  - cloudflare-acme-issuer.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: cert-manager
    path: deploy-args-patch.yaml
