apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
spec:
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller-metrics
  endpoints:
    - port: prometheus
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller-metrics
  name: ingress-nginx-service
  namespace: ingress-nginx
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: prometheus
      port: 10254
      targetPort: prometheus
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
