apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: topolvm
spec:
  namespaceSelector:
    matchNames:
      - topolvm-system
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: topolvm
  name: topolvm-service
  namespace: topolvm-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    app.kubernetes.io/name: topolvm
