apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  namespaceSelector:
    matchNames:
      - velero
  endpoints:
    - port: http-monitoring
      interval: 15s
      path: /metrics
