apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocis
  namespace: ocis
spec:
  interval: 1m
  url: https://github.com/owncloud/ocis-charts.git
  ref:
    branch: stable-5
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
  namespace: ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/ocis
      version: '0.5.*'
      sourceRef:
        kind: GitRepository
        name: ocis
        namespace: ocis
      interval: 12h
  values:
    secretRefs:
      ldapSecretRef: ocis-secrets
    image:
      repository: owncloud/ocis
      tag: 5.0.6
    logging:
      # -- Log level. Valid values: `panic`, `fatal`, `error`, `warn`, `info`, `debug`, `trace`.
      level: 'trace'
    externalDomain: ocis.didactik.labs
    insecure:
      oidcIdpInsecure: true
      ocisHttpApiInsecure: true
    http:
      cors:
        allow_origins:
          - '*'
          - 'localhost'
          - 'auth.didactiklabs.io'
          - 'ocis.didactik.labs'
    features:
      basicAuthentication: false
      externalUserManagement:
        enabled: true
        oidc:
          issuerURI: https://auth.didactiklabs.io/application/o/ocis/
          userIDClaim: preferred_username
          userIDClaimAttributeMapping: username
          webClientID: Ocis
          accessTokenVerifyMethod: 'jwt'
          roleAssignment:
            enabled: true
            # -- The name of the OIDC claim holding the role assignment
            claim: groups
            # -- Configure the mapping for the role assignment
            mapping:
              - role_name: admin
                claim_value: 'authentik Admins'
              - role_name: user
                claim_value: ocisUser
        ldap:
          writeable: false
          uri: ldap://ak-outpost-ldap.authentik
          certTrusted: true
          insecure: true
          bindDN: cn=ldapbind,ou=users,DC=ldap,DC=goauthentik,DC=io
          user:
            schema:
              # -- LDAP Attribute to use as the unique id for users. This should be a stable globally unique id like a UUID.
              id: uid
              # -- Set this to true if the defined `id` attribute for users is of the `OCTETSTRING` syntax. This is e.g. required when using the `objectGUID` attribute of Active Directory for the user ID`s.
              idIsOctetString: false
              # -- LDAP Attribute to use for the email address of users.
              mail: mail
              # -- LDAP Attribute to use for the displayname of users.
              displayName: displayName
              # -- LDAP Attribute to use for username of users.
              userName: cn
            # -- Search base DN for looking up LDAP users.
            baseDN: ou=users,dc=ldap,DC=goauthentik,DC=io
            # -- LDAP search scope to use when looking up users. Supported values are `base`, `one` and `sub`.
            scope: sub
            # -- Type of substring search filter to use for substring searches for users. Possible values: `initial` for doing prefix only searches, `final` for doing suffix only searches or `any` for doing full substring searches
            substringFilterType: any
            # -- LDAP filter to add to the default filters for user search like `(objectclass=ownCloud)`.
            filter: (objectClass=user)
            # -- The object class to use for users in the default user search filter like `inetOrgPerson`.
            objectClass: user
          group:
            schema:
              # -- LDAP Attribute to use as the unique ID for groups. This should be a stable globally unique ID like a UUID.
              id: uid
              # -- Set this to true if the defined `id` attribute for groups is of the `OCTETSTRING` syntax. This is e.g. required when using the `objectGUID` attribute of Active Directory for the group ID`s.
              idIsOctetString: false
              # -- LDAP Attribute to use for the email address of groups (can be empty).
              mail:
              # -- LDAP Attribute to use for the displayname of groups (often the same as groupname attribute).
              displayName: cn
              # -- LDAP Attribute to use for the name of groups.
              groupName: cn
              # -- LDAP Attribute that is used for group members.
              member: member
            # -- Search base DN for looking up LDAP groups.
            baseDN: ou=groups,dc=ldap,DC=goauthentik,DC=io
            createBaseDN: ou=groups,dc=ldap,DC=goauthentik,DC=io
            # -- LDAP search scope to use when looking up groups. Supported values are `base`, `one` and `sub`.
            scope: sub
            # -- LDAP filter to add to the default filters for group searches.
            filter: (objectClass=group)
            # -- The object class to use for groups in the default group search filter like `groupOfNames`.
            objectClass: group
    replicas: 1
    services:
      nats:
        persistence:
          enabled: true
          chownInitContainer: true
          accessModes:
            - ReadWriteOnce
          size: 500Mi
      search:
        persistence:
          enabled: true
          chownInitContainer: true
          accessModes:
            - ReadWriteOnce
          size: 500Mi
      storagesystem:
        persistence:
          enabled: true
          chownInitContainer: true
          accessModes:
            - ReadWriteOnce
          size: 500Mi
      storageusers:
        storageBackend:
          driver: ocis
        persistence:
          enabled: true
          chownInitContainer: true
          accessModes:
            - ReadWriteOnce
          size: 1Gi
        maintenance:
          cleanUpExpiredUploads:
            enabled: true
            schedule: '0 */6 * * *'
            uploadExpiration: 86400
          purgeExpiredTrashBinItems:
            enabled: true
            schedule: '0 */6 * * *'
            personalDeleteBefore: 30d
            projectDeleteBefore: 30d
      store:
        persistence:
          enabled: true
          chownInitContainer: true
          accessModes:
            - ReadWriteOnce
          size: 500Mi
      thumbnails:
        persistence:
          enabled: true
          chownInitContainer: true
          accessModes:
            - ReadWriteOnce
          size: 500Mi
        maintenance:
          cleanUpOldThumbnails:
            enabled: true
            schedule: '0 */6 * * *'
            deleteBefore: 30
            method: atime
      web:
        config:
          disableFeedbackLink: true
          apps:
            - files
            - search
            - text-editor
            - pdf-viewer
            - external
          oidc:
            webClientID: Ocis
            webClientScope: 'openid profile email'
        persistence:
          enabled: true
          chownInitContainer: true
          accessModes:
            - ReadWriteOnce
          size: 500Mi
