apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .aws_access_key_id }}
          aws_secret_access_key ={{ .aws_secret_access_key }}
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: secrets/minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: aws_secret_access_key
      remoteRef:
        key: secrets/minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-ui-keys
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: velero-ui-keys
  data:
    - secretKey: TOKEN_KEY
      remoteRef:
        key: secrets/velero-ui
        property: TOKEN_KEY
    - secretKey: admin-password
      remoteRef:
        key: secrets/velero-ui
        property: admin-password
