apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .aws_access_key_id }}
          aws_secret_access_key ={{ .aws_secret_access_key }}
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: secrets/minio
      property: AWS_ACCESS_KEY_ID
  - secretKey: aws_secret_access_key
    remoteRef:
      key: secrets/minio
      property: AWS_SECRET_ACCESS_KEY
