apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-watchdog
  labels:
    app: webui-watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui-watchdog
  template:
    metadata:
      labels:
        app: webui-watchdog
    spec:
      serviceAccountName: velero-ro
      containers:
        - name: watchdog
          image: dserio83/velero-watchdog:0.1.6
          imagePullPolicy: Always
          env:
            - name: API_ENDPOINT_URL
              value: "0.0.0.0"
            - name: API_ENDPOINT_PORT
              value: "8001"
            - name: PROCESS_CYCLE_SEC
              value: "1800"
            - name: BACKUP_ENABLE
              value: "True"
            - name: SCHEDULE_ENABLE
              value: "True"
            - name: K8S_INCLUSTER_MODE
              value: "True"
            - name: EXPIRES_DAYS_WARNING
              value: "20"
            - name: TELEGRAM_ENABLE
              value: "False"
            - name: EMAIL_ENABLE
              value: "False"
            - name: SLACK_ENABLE
              value: "False"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1256Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8001
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: velero-ui-report
spec:
  schedule: "0 */12 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: velero-ro
          containers:
            - name: velero-watchdog-report
              image: dserio83/velero-watchdog:latest
              command: ["python3", "watchdog.py"]
              imagePullPolicy: Always
              env:
                - name: PROCESS_CYCLE_SEC
                  value: "1800"
                - name: BACKUP_ENABLE
                  value: "True"
                - name: SCHEDULE_ENABLE
                  value: "True"
                - name: K8S_INCLUSTER_MODE
                  value: "True"
                - name: EXPIRES_DAYS_WARNING
                  value: "20"
                - name: TELEGRAM_ENABLE
                  value: "False"
                - name: EMAIL_ENABLE
                  value: "False"
                - name: SLACK_ENABLE
                  value: "False"
          restartPolicy: Never
