apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-ro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ro-resources
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-ro
subjects:
- kind: ServiceAccount
  name: velero-ro
  namespace: velero
roleRef:
  kind: ClusterRole
  name: ro-resources
  apiGroup: rbac.authorization.k8s.io
