apiVersion: v1
kind: ConfigMap
metadata:
  name: paralus-kratos-config
  namespace: default
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: paralus
  annotations:
data:
  # Render the kratos config:
  'kratos.yaml': |
    courier:
      smtp: {}
    identity:
      default_schema_id: default
      schemas:
      - id: default
        url: file:///etc/config/identity.schema.v1.json
    selfservice:
      flows:
        recovery:
          enabled: true
        registration:
          after:
            oidc:
              hooks:
              - hook: session
            password:
              hooks:
              - hook: session
          lifespan: 10m
        settings:
          privileged_session_max_age: 15m
      methods:
        oidc:
          enabled: true
        password:
          enabled: true
    serve:
      admin:
        port: 4434
      public:
        cors:
          allowed_headers:
          - Authorization
          - Cookie
          - Content-Type
          - X-Session-Token
          enabled: true
          exposed_headers:
          - Content-Type
          - Set-Cookie
        port: 4433
    version: v0.11.0
  # Render the identity schemas to disk:
  identity.schema.v1.json: |
    {
      "$id": "https://schemas.paralus.io/email-password/identity.schema.v1.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "first_name": {
              "title": "First name",
              "type": "string",
              "pattern": "^.*$"
            },
            "last_name": {
              "title": "Last name",
              "type": "string",
              "pattern": "^.*$"
            },
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "idp_groups": {
              "type": "array",
              "title": "IDP groups",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }
