apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-server-config
  labels:
    app.kubernetes.io/part-of: paralus
    app.kubernetes.io/name: relay
    app.kubernetes.io/instance: paralus
    app.kubernetes.io/component: configuration
data:
  PARALUS_RELAY_PEERSERVICE: https://paralus:10001
  SENTRY_ADDR: paralus:10000
  AUDIT_PATH: '/audit-logs'
