apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paralus-postgres
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paralus-postgres
  data:
    - secretKey: username
      remoteRef:
        key: secrets/paralus/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/paralus/postgres
        property: password
