apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paralus-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paralus-secrets
    template:
      engineVersion: v2
      data:
        DSN: 'postgres://{{ .username }}:{{ .password }}@{{ .host }}:5432/{{ .database }}'
        DB_ADDR: '{{ .host }}'
        DB_USER: '{{.username }}'
        DB_PASSWORD: '{{ .password }}'
        DB_NAME: '{{ .database }}'
        database: '{{ .database }}'
        username: '{{ .username }}'
        password: '{{ .password }}'
        smtpConnectionURI: 'smtps://{{ .smtpUsername }}:{{ .smtpPassword }}@{{ .smtpHost }}:1025/?skip_ssl_verify=true'
  data:
    - secretKey: username
      remoteRef:
        key: secrets/paralus/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/paralus/postgres
        property: password
    - secretKey: host
      remoteRef:
        key: secrets/paralus/postgres
        property: host
    - secretKey: database
      remoteRef:
        key: secrets/paralus/postgres
        property: database
    - secretKey: smtpUsername
      remoteRef:
        key: secrets/paralus/smtp
        property: username
    - secretKey: smtpPassword
      remoteRef:
        key: secrets/paralus/smtp
        property: password
    - secretKey: smtpHost
      remoteRef:
        key: secrets/paralus/smtp
        property: host
