apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main
spec:
  inhibitRules:
    - sourceMatch:
        - matchType: '='
          name: 'severity'
          value: 'critical'
      targetMatch:
        - matchType: '=~'
          name: 'severity'
          value: 'warning|info|none'
      equal:
        - namespace
        - alertname
    - sourceMatch:
        - matchType: '='
          name: 'severity'
          value: 'warning'
      targetMatch:
        - matchType: '=~'
          name: 'severity'
          value: 'info|none'
      equal:
        - namespace
        - alertname
    - sourceMatch:
        - matchType: '='
          name: 'alertname'
          value: 'InfoInhibitor'
      targetMatch:
        - matchType: '='
          name: 'severity'
          value: 'info'
      equal:
        - namespace
  route:
    groupBy:
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: discord
    routes:
      - matchers:
          - matchType: '=~'
            name: 'alertname'
            value: 'InfoInhibitor|Watchdog'
        receiver: 'null'
  receivers:
    - name: 'null'
    - name: discord
      discordConfigs:
        - sendResolved: true
          apiURL:
            name: grafana-secrets
            key: discordwebhookurl
          title: |-
            **[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}{{ .CommonLabels.alertname }}{{ end }}**
          message: |-
            {{ range .Alerts }}
            ---
            **🚨 Alert:** {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity | toUpper }}`{{ end }}

            **📄 Description:**
            ```
            {{ if ne .Annotations.description ""}}{{ .Annotations.description }}{{ else }}N/A{{ end }}
            ```

            **🔍 Details:**
            {{ range .Labels.SortedPairs }}
            • **{{ .Name }}**: `{{ .Value }}`
            {{ end }}
            ---
            {{ end }}
