apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: default
spec:
  instanceSelector:
    matchLabels:
      dashboards: 'grafana'
  route:
    receiver: discord
    group_by:
      - grafana_folder
      - alertname
      - severity
    routes:
      - receiver: discord
        object_matchers:
          - - severity
            - =
            - critical
      - receiver: discord
        object_matchers:
          - - severity
            - =
            - warning
