apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana-ing
spec:
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
  podSelector:
    matchLabels:
      app: grafana
  policyTypes:
    - Ingress
