apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: discord
spec:
  name: discord
  type: 'discord'
  instanceSelector:
    matchLabels:
      dashboards: grafana
  settings:
  valuesFrom:
    - targetPath: url
      valueFrom:
        secretKeyRef:
          name: grafana-secrets
          key: discordwebhookurl
