apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
spec:
  replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: 'topolvm-hdd'
        resources:
          requests:
            storage: 100Gi
