apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: client-id
      remoteRef:
        key: secrets/grafana/config
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: secrets/grafana/config
        property: client-secret
    - secretKey: discordwebhookurl
      remoteRef:
        key: secrets/grafana/config
        property: discordwebhookurl
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rootca
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rootca
  data:
    - secretKey: 'ca.crt'
      remoteRef:
        key: secrets/certs/didactiklabs-rootca
        property: ca.crt
