apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-secrets
  postgresql:
    shared_preload_libraries:
      - 'vectors.so'
  storage:
    size: 8Gi
---
