apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-secrets
      import:
        type: monolith
        databases:
          - 'immich'
        roles:
          - 'immich'
        source:
          externalCluster: legacy-pg
  postgresql:
    shared_preload_libraries:
      - 'vectors.so'
  storage:
    size: 8Gi
  externalClusters:
    - name: legacy-pg
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: immich-postgresql.immich
        user: immich
        dbname: immich
      password:
        name: immich-secrets
        key: password
---
