apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: '0.8.5'
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  values:
    env:
      REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
      DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
      DB_USERNAME: '{{ .Values.postgresql.global.postgresql.auth.username }}'
      DB_DATABASE_NAME: '{{ .Values.postgresql.global.postgresql.auth.database }}'
      IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            key: password
            name: immich-secrets
    image:
      tag: v1.123.0
    immich:
      metrics:
        enable: true
      probes:
        liveness:
          spec:
            initialDelaySeconds: 300
        readiness:
          spec:
            initialDelaySeconds: 300
        startup:
          spec:
            failureThreshold: 60
            periodSeconds: 10
      persistence:
        library:
          existingClaim: immich-data
    # Dependencies
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            existingSecret: immich-secrets
      primary:
        resourcesPreset: 'medium'
        persistence:
          accessModes:
            - ReadWriteOnce
          enabled: true
          size: 10Gi
    redis:
      enabled: true
      architecture: replication
    # Immich components
    server:
      enabled: true
      serviceAccount:
        create: true
        name: 'immich'
      automountServiceAccountToken: true
      ingress:
        main:
          enabled: false
    machine-learning:
      enabled: true
      env:
        TRANSFORMERS_CACHE: /cache
