apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich
spec:
  parentRefs:
    - name: public
      namespace: istio-system
      sectionName: https
  hostnames:
    - photos.didactiklabs.io
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
