apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
spec:
  storageClassName: topolvm-hdd
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 800Gi
