apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: topolvm-hdd
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 800Gi
