apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-secrets
  data:
    - secretKey: postgres-password
      remoteRef:
        key: secrets/immich/postgres
        property: postgres-password
    - secretKey: password
      remoteRef:
        key: secrets/immich/postgres
        property: password
