apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kamaji-postgres
spec:
  instances: 3
  enableSuperuserAccess: true
  superuserSecret:
    name: kamaji-postgres-superuser
  storage:
    size: 20Gi
