apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: velero
spec:
  groups:
    - name: velero-failures
      rules:
        - alert: VeleroBackupPartialFailures
          annotations:
            message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
          expr: |-
            velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
          for: 5m
          labels:
            severity: warning
        - alert: VeleroBackupFailures
          annotations:
            message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
          expr: |-
            velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
          for: 5m
          labels:
            severity: warning
        - alert: VeleroDailyScheduleMissingBackups
          annotations:
            message: Velero schedule {{ $labels.schedule }} has not produced a backup in the last 24 hours.
          expr: |-
            time() - max_over_time(velero_backup_last_successful_timestamp{schedule!=""}[1d]) > 100000
            unless velero_backup_last_successful_timestamp{schedule="immich-data"}
          for: 15m
          labels:
            severity: warning
        - alert: VeleroWeeklyScheduleMissingBackups
          annotations:
            message: Velero schedule {{ $labels.schedule }} has not produced a backup in the last 168 hours.
          expr: |-
            time() - max_over_time(velero_backup_last_successful_timestamp{schedule="immich-data"}[1d]) > 608400
          for: 15m
          labels:
            severity: warning
