apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atuin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atuin
    spec:
      containers:
        - args:
            - server
            - start
          env:
            - name: ATUIN_DB_URI
              valueFrom:
                secretKeyRef:
                  name: atuin-postgres
                  key: database_uri
            - name: ATUIN_HOST
              value: 0.0.0.0
            - name: ATUIN_PORT
              value: '8888'
            - name: ATUIN_OPEN_REGISTRATION
              value: 'true'
          image: ghcr.io/atuinsh/atuin:0056c72
          name: atuin
          ports:
            - name: http
              containerPort: 8888
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /config
              name: atuin-claim0
      volumes:
        - name: atuin-claim0
          persistentVolumeClaim:
            claimName: atuin-claim0
