apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-postgres
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: atuin-postgres
    template:
      engineVersion: v2
      data:
        database_uri: "postgres://{{ .username }}:{{ .password }}@atuin-postgres-rw/{{ .database }}"
        database: "{{ .database }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: secrets/atuin/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/atuin/postgres
        property: password
    - secretKey: database
      remoteRef:
        key: secrets/atuin/postgres
        property: database
