apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  targetNamespace: vault
  interval: 1h0m0s
  chart:
    spec:
      chart: vault
      version: "0.28.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    global:
      tlsDisable: true
    server:
      dataStorage:
        enabled: true
        size: 10Gi
        mountPath: "/vault/data"
        accessMode: ReadWriteOnce
      standalone:
        enabled: "-"
        config: |
          ui = true
          listener "tcp" {
            address       = "0.0.0.0:8200"
          }
          storage "file" {
            path = "/vault/data"
          }
      readinessProbe:
        enabled: false
      livenessProbe:
        enabled: false
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: root-didactiklabs
        pathType: Prefix
        hosts:
          - host: vault.didactik.labs
            paths: "/"
        tls:
        - secretName: vault-tls
          hosts:
          - vault.didactik.labs
    ui:
      enabled: true
      publishNotReadyAddresses: true
      activeVaultPodOnly: false
      serviceType: "ClusterIP"
      externalPort: 443
      targetPort: 8200
    injector:
      enabled: false
    csi:
      enabled: false

