namespace: grafana

resources:
  - ../../base

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      version: v1
      group: apps
      name: grafana-operator-controller-manager
  - target:
      kind: ClusterRole
    patch: |
      - op: replace
        path: /kind
        value: Role
  - target:
      kind: ClusterRoleBinding
    patch: |
      - op: replace
        path: /kind
        value: RoleBinding
      - op: replace
        path: /roleRef/kind
        value: Role
