kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: gatewayapi
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
        - https://auth.didactiklabs.io
        - https://photos.didactiklabs.io
        - https://minio.didactiklabs.io
