kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: ingress
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx_didactiklabs
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    ingress:
      namespaceSelector:
        any: true
      selector:
        matchLabels:
          probe: enabled
