kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-apiserver
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx_with_sa_auth
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
        - https://kubernetes.default.svc/readyz
