apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rootca
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rootca
  data:
    - secretKey: ca.crt
      remoteRef:
        key: secrets/certs/didactiklabs-rootca
        property: ca.crt
