apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://openebs.github.io/lvm-localpv
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  targetNamespace: openebs
  install:
    createNamespace: true
  chart:
    spec:
      chart: lvm-localpv
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 1h0m0s
  values:
    lvmNode:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        effect: "NoSchedule"
