apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-frieren
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: local.csi.openebs.io
allowVolumeExpansion: true
parameters:
  storage: "lvm"
  volgroup: "openebs"
  shared: "yes"
allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/nodename
        values:
          - frieren
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-gojo
provisioner: local.csi.openebs.io
allowVolumeExpansion: true
parameters:
  storage: "lvm"
  volgroup: "openebs"
  shared: "yes"
allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/nodename
        values:
          - gojo
