apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kamaji-serving-cert
  namespace: kamaji-system
spec:
  dnsNames:
    - kamaji-webhook-service.kamaji-system.svc
    - kamaji-webhook-service.kamaji-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kamaji-selfsigned-issuer
  secretName: kamaji-webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kamaji-selfsigned-issuer
  namespace: kamaji-system
spec:
  selfSigned: {}
