  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kamaji
    labels:
      app.kubernetes.io/name: kamaji
      app.kubernetes.io/instance: kamaji
      app.kubernetes.io/component: controller-manager
    namespace: kamaji-system
  spec: clastix/kamaji:edge-25.3.2
