image:
  tag: edge-24.12.1
etcd:
  deploy: false
datastore:
  enabled: true
  nameOverride: postgres-cnpg
  driver: PostgreSQL
  endpoints: ["kamaji-postgres-rw.kamaji-system.svc:5432"]
  basicAuth:
    usernameSecret:
      name: kamaji-postgres-superuser
      namespace: kamaji-system
      keyPath: username
    passwordSecret:
      name: kamaji-postgres-superuser
      namespace: kamaji-system
      keyPath: password
  tlsConfig:
    enabled: false
    certificateAuthority:
      certificate:
        name: kamaji-postgres-ca
        namespace: kamaji-system
        keyPath: ca.crt
