apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio
  data:
  - secretKey: MINIO_ROOT_USER
    remoteRef:
      key: secrets/minio
      property: MINIO_ROOT_USER
  - secretKey: MINIO_ROOT_PASSWORD
    remoteRef:
      key: secrets/minio
      property: MINIO_ROOT_PASSWORD
  - secretKey: MINIO_IDENTITY_OPENID_CLIENT_SECRET
    remoteRef:
      key: secrets/minio
      property: MINIO_IDENTITY_OPENID_CLIENT_SECRET
