apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kamaji-postgres-superuser
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kamaji-postgres-superuser
  data:
    - secretKey: username
      remoteRef:
        key: secrets/kamaji/postgres
        property: superuser-name
    - secretKey: password
      remoteRef:
        key: secrets/kamaji/postgres
        property: superuser-password
