apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: kube-prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: 'grafana'
  resyncPeriod: 1m
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    url: 'http://prometheus-k8s.monitoring.svc:9090'
    isDefault: true
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': '5s'
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      dashboards: 'grafana'
  resyncPeriod: 1m
  datasource:
    name: alertmanager
    type: alertmanager
    access: proxy
    url: 'http://alertmanager-main.monitoring.svc:9093'
    jsonData:
      implementation: prometheus
      'tlsSkipVerify': true
      'timeInterval': '5s'
    isDefault: true

