apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-controller-manager
    app.kubernetes.io/part-of: kube-prometheus
spec:
  selector:
    component: kube-controller-manager
  ports:
    - name: https-metrics
      protocol: TCP
      port: 443
      targetPort: 10257
---
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
    app.kubernetes.io/part-of: kube-prometheus
spec:
  ports:
    - name: https-metrics
      port: 443
      targetPort: 10259 # Typically, the kube-scheduler listens on 10259 for HTTPS metrics
  selector:
    component: kube-scheduler

