apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  monitorNamespace: monitoring
  configuration:
    developerConfiguration:
      featureGates:
        - BlockVolume
