apiVersion: v1
kind: Namespace
metadata:
  name: kamaji-system
---
apiVersion: v1
kind: Secret
metadata:
  name: capi-vars
  namespace: kamaji-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  version: v0.13.0
  configSecret:
    name: capi-vars
  fetchConfig:
    url: https://github.com/clastix/cluster-api-control-plane-provider-kamaji/releases/v0.13.0/control-plane-components.yaml
