apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: v1
kind: Secret
metadata:
  name: capi-vars
  namespace: capi-system
stringData:
  CLUSTER_TOPOLOGY: "true"
  EXP_CLUSTER_RESOURCE_SET: "true"
  EXP_MACHINE_SET_PREFLIGHT_CHECKS: "true"
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.8.4
  configSecret:
    name: capi-vars
  manager:
    metrics:
      bindAddress: '0.0.0.0:8080'
