apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invidious-postgres
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invidious-postgres
  data:
    - secretKey: username
      remoteRef:
        key: secrets/invidious/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/invidious/postgres
        property: password
    - secretKey: hmac_key
      remoteRef:
        key: secrets/invidious/postgres
        property: hmac_key
