apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-frieren
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1200Gi
