apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: casdoor-postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: casdoor
      owner: casdoor
      secret:
        name: casdoor-secrets
  storage:
    size: 8Gi
---
