apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm-csi
  namespace: flux-system
spec:
  targetNamespace: topolvm-system
  chart:
    spec:
      chart: topolvm
      version: 15.5.1
      sourceRef:
        kind: HelmRepository
        name: topolvm-csi
  interval: 1h0m0s
  values:
    controller:
      replicaCount: 1
    lvmd:
      args: ['--lvm-path', '/run/current-system/sw/bin/lvm']
      tolerations:
        - key: 'dedicated'
          operator: 'Equal'
          effect: 'NoSchedule'
      deviceClasses:
        - name: ssd-thin
          type: thin
          volume-group: kubernetes
          default: true
          spare-gb: 10
          thin-pool:
            name: 'pool0'
            overprovision-ratio: 5.0
        - name: hdd-thin
          type: thin
          volume-group: hdd
          spare-gb: 10
          thin-pool:
            name: 'pool0'
            overprovision-ratio: 5.0
    node:
      args: ['--lvm-path', '/run/current-system/sw/bin/lvm']
      tolerations:
        - key: 'dedicated'
          operator: 'Equal'
          effect: 'NoSchedule'
    storageClasses:
      - name: topolvm
        storageClass:
          fsType: xfs
          isDefaultClass: true
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
