apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: topolvm
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
    velero.io/csi-volumesnapshot-class: "true"
driver: topolvm.io
deletionPolicy: Delete
