- op: add
  path: "/spec/template/spec/containers/0/args/-"
  value:
    --enable-ssl-passthrough

- op: add
  path: "/spec/template/spec/containers/0/args/-"
  value:
    --publish-service=ingress-nginx/ingress-nginx-controller
