apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/baremetal/deploy.yaml

patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx

- path: service-patch.yaml
  target:
    version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx

- path: ingress-config-patch.yaml
  target:
    version: v1
    kind: ConfigMap
    name: ingress-nginx-controller
    namespace: ingress-nginx

- path: class-patch.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: IngressClass
    name: nginx
