apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: attic-postgres
  annotations:
    cnpg.io/skipWalArchiving: "enabled"
spec:
  instances: 1
  bootstrap:
    initdb:
      database: attic
      owner: attic
      secret:
        name: attic-postgres
  postgresql:
    parameters:
      wal_level: minimal
      max_wal_senders: "0"
  backup:
    barmanObjectStore:
      endpointURL: http://minio-frieren.minio.svc:9000
      destinationPath: 's3://cnpg/attic'
      s3Credentials:
        accessKeyId:
          name: minio-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-credentials
          key: ACCESS_SECRET_KEY
    retentionPolicy: '14d'
  storage:
    size: 8Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: attic
  namespace: attic
spec:
  schedule: '0 0 12 * * *'
  backupOwnerReference: self
  cluster:
    name: attic-postgres
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: secrets/minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: secrets/minio
        property: AWS_SECRET_ACCESS_KEY
