apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: attic-config
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: attic-config
  data:
    - secretKey: ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64
      remoteRef:
        key: secrets/attic/config
        property: ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64
