apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: '0.11.0'
      sourceRef:
        kind: HelmRepository
        name: arc
      interval: 12h
  values:
    runnerScaleSetName: 'didactiklabs-runners'
    githubConfigUrl: 'https://github.com/didactiklabs'
    githubConfigSecret: 'github-auth-secret'
    minRunners: 0
    maxRunners: 10
    template:
      spec:
        containers:
          - name: runner
            command: ['/home/runner/run.sh']
            image: banhcanh/action-runner:2.323.0
            resources:
              limits:
                cpu: '4'
                memory: '8Gi'
              requests:
                cpu: '4'
                memory: '8Gi'
