apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: '0.11.0'
      sourceRef:
        kind: HelmRepository
        name: arc
      interval: 12h
---
