apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc-system
spec:
  interval: 24h
  url: https://actions-runner-controller.github.io/actions-runner-controller
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: '0.10.1'
      sourceRef:
        kind: HelmRepository
        name: arc
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: '0.10.1'
      sourceRef:
        kind: HelmRepository
        name: arc
      interval: 12h
  values:
    runnerScaleSetName: 'didactiklabs-runners'
    githubConfigUrl: 'https://github.com/didactiklabs'
    githubConfigSecret: 'github-auth-secret'
    minRunners: 0
    maxRunners: 1
    template:
      spec:
        containers:
          - name: runner
            command: ['/home/runner/run.sh']
