apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-auth-secret
  data:
    - secretKey: github_app_id
      remoteRef:
        key: secrets/arc/github_auth
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: secrets/arc/github_auth
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: secrets/arc/github_auth
        property: github_app_private_key
