apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zitadel-secrets
  data:
    - secretKey: username
      remoteRef:
        key: secrets/zitadel/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/zitadel/postgres
        property: password
    - secretKey: database
      remoteRef:
        key: secrets/zitadel/postgres
        property: database
    - secretKey: adminUsername
      remoteRef:
        key: secrets/zitadel/config
        property: adminUsername
    - secretKey: adminPassword
      remoteRef:
        key: secrets/zitadel/config
        property: adminPassword
    - secretKey: masterkey
      remoteRef:
        key: secrets/zitadel/config
        property: masterkey
