apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: zitadel
      version: 8.11.2
      sourceRef:
        kind: HelmRepository
        name: zitadel
  values:
    # Default values for zitadel.
    zitadel:
      # https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
      configmapConfig:
        ExternalSecure: true
        Machine:
          Identification:
            Hostname:
              Enabled: true
            Webhook:
              Enabled: false
      # https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
      secretConfig:
      # Reference the name of a secret that contains ZITADEL configuration.
      # configSecretName: zitadel-secrets
      # configSecretKey: config.yaml
      # ZITADEL uses the masterkey for symmetric encryption.
      # You can generate it for example with tr -dc A-Za-z0-9 </dev/urandom | head -c 32
      # Reference the name of the secret that contains the masterkey. The key should be named "masterkey".
      masterkeySecretName: 'zitadel-secrets'
      # The Secret containing the certificate at key tls.crt and tls.key for listening on HTTPS
      # serverSslCrtSecret: 'zitadel-server-tls'
      selfSignedCert:
        enabled: false
    replicaCount: 3
    image:
      repository: ghcr.io/zitadel/zitadel
      pullPolicy: IfNotPresent
      tag: 'v2.68.1'
    # Annotations to add to the configMap
    serviceAccount:
      create: true
    env:
      - name: ZITADEL_FIRSTINSTANCE_INSTANCENAME
        value: didactikLabs
      - name: ZITADEL_FIRSTINSTANCE_ORG_NAME
        value: didactikLabs
      - name: ZITADEL_TLS_ENABLED
        value: 'false'
      - name: ZITADEL_EXTERNALDOMAIN
        value: 'zitadel.didactiklabs.io'
      - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED
        value: 'false'
      - name: ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED
        value: 'false'
      - name: ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_ALLOWREGISTER
        value: 'false'
      - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: adminUsername
      - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: adminPassword
      - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: adminUsername
      - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: adminPassword
      - name: ZITADEL_DATABASE_POSTGRES_HOST
        value: zitadel-postgres-rw
      - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
        value: disable
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
        value: disable
      - name: ZITADEL_DATABASE_POSTGRES_PORT
        value: '5432'
      - name: ZITADEL_DATABASE_POSTGRES_DATABASE
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: database
      - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: username
      - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: password
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: username
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-secrets
            key: password
    extraManifests: []
